services:
  - type: web
    name: coinex-fastapi-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bot:app --host 0.0.0.0 --port $PORT"
